server:
  port: 0

spring:
  application:
    name: user-service
  profiles:
    active: dev
  datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/myuser
      platform: postgres
      username: admin3
      password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    defer-datasource-initialization: true
  sql.init.mode: always


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.example.usermicroservice_220812_v2: DEBUG
